version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/tecno-backend
file_exists_behavior: OVERWRITE

hooks:
  ApplicationStop:
  - location: scripts/application_stop.sh
    timeout: 120
    runas: root

  DownloadBundle:
  - location: scripts/download_bundle.sh
    timeout: 120
    runas: root

  BeforeInstall:
  - location: scripts/before_install.sh
    timeout: 120
    runas: root

  Install:
  - location: scripts/install.sh
    timeout: 120
    runas: root

  AfterInstall:
  - location: scripts/after_install.sh
    timeout: 120
    runas: root


  ApplicationStart:
  - location: scripts/application_start.sh
    timeout: 120
    runas: root
