version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/tecno-backend
file_exists_behavior: OVERWRITE

hooks:
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 120
      runas: ubuntu
