name: ec2-dev-push

on:
  push:
    branches:
      - '*'
    
jobs:
  test:
    name: deploy-code
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Files
        uses: actions/checkout@v3
        
      - name: Deploy Code to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.EC2_HOST_DNS }}
          REMOTE_USER: ${{ secrets.EC2_USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR_DEV }}
      
      - name: Build and Redeploy Code
        uses: appleboy/ssh-action@master
        env:
          TARGET: ${{ secrets.TARGET_DIR_DEV }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key_path: ${{ secrets.EC2_SSH_KEY }}
          envs: TARGET
          script: ./${{ secrets.TARGET_DIR_DEV }}/.github/scripts/update.sh
